### ISSUE TITLE
Update README to introduce `create-seia-app`

### ISSUE THREAD

**Issue by abiriadev** [abiriadev/seia#22]
## Problem

the current README does not mention `create-seia-app` at all. It should introduce how to use `create-seia-app` for easier development.

**Comment by HarunaMahjong** [comment]
지금 리드미 파일에 내용을 추가중입니다...ㅇㅅㅇb

**Comment by abiriadev** [comment]
@HarunaMahjong 감사합니다!! :pray:

이슈 어사인해 드릴게요!
