### ISSUE TITLE
 Occurred Internal Server Error in yarn berry plug'n play

### ISSUE THREAD

**Issue by jureuk7** [abiriadev/seia#25]
**Describe the bug**
When starting Yarn berry Plug'n Play, an internal server error occurred.

**To Reproduce**
1. create project using `create-seia-app`, set packageManager to `yarn berry`
2. set `nodeLinker` option to `pnp` in `yarnrc.yml`
3. run build, and start
4. see 500 internal server error

**Screenshots**
<img width="785" alt="image" src="https://github.com/abiriadev/seia/assets/26669223/aaef6704-6342-40d0-b9ce-05e84507ca3a">

**Desktop (please complete the following information):**
 - OS:  macOS 14.4.1
 - Browser: Arc

**Comment by abiriadev** [comment]
@jureuk7 Thank you for reporting! I can reproduce the same issue!

I will work for it now!

**Comment by abiriadev** [comment]
@jureuk7 Will you try again with `create-seia-app@latest`? I have merged a PR addressing this issue: #26

**Comment by jureuk7** [comment]
I just created a new project using create-seia-app@latest and confirmed that it started normally. Thank you for fixing it quickly!
