### ISSUE TITLE
CLI tool to create projects using templates

### ISSUE THREAD

**Issue by gangjun06** [abiriadev/seia#3]
**Is your feature request related to a problem? Please describe.**
Setting up and using these new libraries from scratch can be cumbersome and time-consuming for users.

**Describe the solution you'd like**
I propose the development of a CLI utility called create-seia-app, similar to create-next-app.
This utility would significantly enhance accessibility and ease of use for the project.

**Comment by abiriadev** [comment]
Thank you for the suggestions! I will work on implementing them.

Do you have any ideas for templates that should be supported, such as `typeScript`, `javaScript`, `tailwind`, etc?
