### ISSUE TITLE
Fix typo in README.md and process-polyfill.js

### ISSUE THREAD

**Issue by nemorize** [abiriadev/seia#5]
**Describe the bug**
https://github.com/abiriadev/seia/blob/26278b9282a700e37fcfa4f8dae623e3ef9c2de4/README.md?plain=1#L35
https://github.com/abiriadev/seia/blob/26278b9282a700e37fcfa4f8dae623e3ef9c2de4/packages/seia/src/process-polyfill.ts#L6

**Expected behavior**
`They, install Seia:` in `README.md` should be `Then, install Seia:`.
`'prodection'` in `packages/seia/src/process-polyfill.ts` should be `'production'`.

**Comment by abiriadev** [comment]
@nemorize Thanks for reporting! It will be fixed immediately.

**Comment by abiriadev** [comment]
@nemorize Would you send a pull request for this?

**Comment by nemorize** [comment]
Sure 👍
